#!/bin/bash
#
# $Id: ethconfig,v 1.3 2003/04/11 21:56:05 root Exp $
#
# ETHCONFIG - new and improved version of shell script that
#             will no longer require an external text file
#	      with ip addresses to be bound to network card.
#

IFCONFIG=`which ifconfig`
HOSTNAME=`hostname`

if [ $HOSTNAME = 'host2.lunarhosting.net' ]; then
  NETWORK="65.172.1"
else
  NETWORK="208.16.140"
fi

BCAST="$NETWORK.255"	# broadcast ip address
MASK="255.255.255.128"  # netmask 
INT="eth0"              # the value of your ethernet adapter
OCTET="136"		# first host address bound
LAST="254"		# last host address bound

until [ $OCTET -gt $LAST ]; do
	$IFCONFIG $INT:$OCTET $NETWORK.$OCTET netmask $MASK broadcast $BCAST up
	OCTET=$(($OCTET+1))
done
exit 0
