#!/usr/bin/perl -w

# $Id: noverify,v 1.2 2002/12/31 12:15:31 root Exp $

use strict;
use Authen::PAM;
use Passwd::Linux qw(modpwinfo mgetpwnam);
use Getopt::Long;

my $username; 
my $password;
GetOptions ( 'username=s' => \$username, 'password=s' => \$password, );

## define service to check
my $service = "passwd";

exit &check_password;

sub check_password {
  ## inquiry to PAM
  my $pamh = new Authen::PAM($service, $username, \&my_conv_func);
  #ref(my $pamh = new Authen::PAM($service, $username, \&my_conv_func));
  #  or die "Error code during PAM init!\n";

  ## grab return from auth process. other than 0 equals failure
  my $answer = $pamh->pam_authenticate;

  return $answer;

}

## pre-defined function from Authen::PAM
sub my_conv_func {

  chomp $username;
  chomp $password;

  my @res;
  while ( @_ ) {
      my $code = shift;
      my $msg = shift;
      my $ans = "";


      $ans = $username if ($code == PAM_PROMPT_ECHO_ON() );
      $ans = $password if ($code == PAM_PROMPT_ECHO_OFF() );


      push @res, (PAM_SUCCESS(),$ans);
  }
  push @res, PAM_SUCCESS();
  return @res;
}

